log PHPUnit version

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -129,7 +129,10 @@ jobs:
           php-version: '${{ matrix.php }}'
           extensions: mysql, zip
           coverage: none
-          tools: composer, phpunit:6.5.5
+          tools: composer, phpunit:5.7.27
+
+      - name: phpunit version (global)
+        run: phpunit -v || echo "PHPUnit not found"
 
       - name: Get Composer cache Directory
         if: steps.check_files.outputs.files_exists == 'true'
@@ -149,6 +152,9 @@ jobs:
       - name: Install dependencies
         if: steps.check_files.outputs.files_exists == 'true'
         run: COMPOSER_ROOT_VERSION=dev-master composer install --prefer-dist --no-progress --no-suggest
+
+      - name: phpunit version (composer)
+        run: composer exec phpunit -v || echo "PHPUnit not found"
 
       - name: Configure DB environment
         if: steps.check_files.outputs.files_exists == 'true'
